name: test

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

env:
  CPPFLAGS: "-I/usr/include"
  LDFLAGS: "-L/usr/lib"
  LD_LAIBRARY_PATH: "/usr/lib"

jobs:
  run-tests:
    strategy:
      matrix:
        #os: ["ubuntu:22.04", "almalinux:9"]
        os: ["ubuntu:22.04"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}

    steps:

      - name: Install prerequisite softwares (Ubuntu 22.04)
        if: matrix.os == 'ubuntu:22.04'
        run: |
          apt-get update -y
          apt-get install -y libncurses6 libncurses-dev ncurses-doc libgmp10 libgmp-dev m4 libtool help2man pkg-config gettext automake autoconf libxml2 libxml2-dev libxml2-utils libcjson1 libcjson-dev build-essential libdb-dev

      - name: Install prerequisites (AlmaLinux 9)
        if: matrix.os == 'almalinux:9'
        run: |
          dnf update -y
          dnf install -y gcc gcc-c++ make bison flex automake autoconf diffutils gettext libtool help2man pkgconfig libxml2 libxml2-devel libxml2-utils libdb-devel ncurses ncurses-devel gmp gmp-devel cjson cjson-devel

      - uses: actions/checkout@v4

      # Cache the directory 'opensource-cobol-1.5.2J/vbisam'
      - name: Cache vbisam
        id: vbisam_cache_id
        uses: actions/cache@v4
        with:
          path: opensource-cobol/vbisam
          key: vbisam-key

      # Download vbisam and Build it
      - name: Download vbisam and Build it
        if: steps.vbisam_cache_id.outputs.cache-hit != 'true'
        run: |
          curl -L -o opensource-cobol-1.5.2J.tar.gz https://github.com/opensourcecobol/opensource-cobol/archive/refs/tags/v1.5.2J.tar.gz
          tar zxf opensource-cobol-1.5.2J.tar.gz
          cd opensource-cobol-1.5.2J/vbisam
          ./configure --prefix=/usr/
          make

      # Install vbisam
      - name: Install vbisam
        working-directory: opensource-cobol-1.5.2J/vbisam
        run: |
          make install

      - name: Install GnuCOBOL
        run: |
          ./configure --prefix=/usr/ --with-xml2 --with-cjson --with-vbisam
          make
          make install

      - name: Run custom tests
        run: |
          make check

      - name: Run COBOL85 tests
        run: |
          make test